services:
  - type: web
    name: ventas-e-inventario
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
    healthCheckPath: /api/version
    autoDeploy: true
